######ALIASES######

######SHELL ALIASES######
# echo "cl for clear and replace header" 
    alias "cl=clear;~/Scripts/mnemosyne3.sh"
# echo "rs for reload shell"
    alias "rs=source ~/.zshrc"
# echo "E for exit shell session"
    alias "E=exit"
######PACKAGE MANAGEMENT#######
# echo "sudo pacman -s"
    alias "pmi=sudo pacman -S"
# echo "sudo pacman -Ss"
    alias "pmq=sudo pacman -Ss"
# echo "pmr = sudo pacman -R"
    alias "pmr=sudo pacman -R"
# echo "fpi for flatpak install"
    alias "fpi=flatpak install"
# echo "fps for flatpak search"
    alias "fps=flatpak search"
# echo "sysctl for systemctl"
    alias "sysctl=sudo systemctl" 
######APPS######
# echo "tm for tmux"
    alias "tm=tmux"
    ###TMUXALIASES###
    # echo "tmks for kill all sessions"
        alias "tmks=tmux kill-session"
    # echo "tmka for kill all servers"
        alias "tmka=tmux kill-server"
    # echo "tmns for new tmux session"
        alias "tmns=tmux new-session"
    # echo tmls for list all tmux sessions"
        alias "tmls=tmux ls"
    # echo "nv for neovim" 
    alias "nv=nvim ."
# echo "mp for mocp"
    alias "mp=mocp"
# echo "xs for xstarter"
    alias "xs=xstarter"
#echo "nf for neofetch"
    alias "nf=neofetch"
######NAVIGATION#######
# echo ".ca for .cache"
    alias ".ca=.cache;ls -a"
# echo ".co for config"
    alias ".co=.config;ls -a"
# echo ".lo for .local"
    alias ".lo=.local;ls -a" 
# echo "DE=Desktop"
    alias "DE=Desktop;ls -a"
# echo "DC for Documents"
    alias "DC=Documents;ls -a"
# echo "DO for Downloads"
    alias "MU=Music;ls -a"
# echo "PI for Pictures"
    alias "PI=Pictures;ls -a"
# echo "SC for Scripts"
    alias "SC=Scripts;ls -a"
# echo "VI for Videos"
    alias "VI=Videos;ls -a"
# echo "H for HOME"
    alias "h=~/;ls -a"
######SSH######
# echo "sshrpi for ssh r3z04gw3"
    alias "sshrpi=ssh -Y c4s3@192.168.0.28"
# echo "sshmthr for ssh mthrbs"
    alias "sshmthr=ssh c4s3@192.168.0.25"
######PWRMANAGEMENT######
# echo "SD for shutdown now"
    alias "SD=sudo shutdown"
# echo "RB for reboot now"
    alias "RB=sudo reboot"
# echo "systemctl suspened for sleep"
    alias "SL=sudo suspend"
# echo "LK for i3lock"
    alias "LK=i3lock"
######SCRIPTS######
# echo "tb for TMBOOT.sh"
    alias "tb=cl;~/Scripts/TMBOOT.sh"
# echo "update script run"
    alias "ud=~/Scripts/update.sh"
# echo "show dracula colours"
    alias "vlad=~/Scripts/vlad.sh"
# echo "show tmux keybindings"
    alias "tmhi=~/Scripts/tmhi.sh"
